from __future__ import annotations

ENABLED = "✅"
DISABLED = "🔴"

EMOJI = {
    "main_menu": "🏠",
    "back": "⬅️",
    "register": "📝",
    "profile": "👤",
    "show_profile": "👤",
    "mystats": "📊",
    "refresh_stats": "🔄",
    "refresh": "🔄",
    "seasons": "🗓️",
    "notify": "🔔",
    "notify_personal": "🔔",
    "targets": "🎯",
    "targets_select": "🎯",
    "targets_table": "📋",
    "targets_assign": "🛠",
    "rules": "📜",
    "complaint": "📣",
    "complaints": "📣",
    "guide": "❓",
    "admin": "🛠",
    "admin_clear_player": "🧹",
    "admin_diagnostics": "🩺",
    "admin_users": "👥",
    "admin_blacklist": "🚫",
    "admin_whitelist": "✅",
    "admin_notify_chat": "🔔",
    "admin_notify": "🔔",
    "admin_monthly_report": "📅",
    "blacklist_add": "➕",
    "blacklist_show": "📋",
    "blacklist_remove": "🗑",
    "whitelist_add": "➕",
    "whitelist_show": "📋",
    "whitelist_remove": "🗑",
    "delete": "🗑",
    "notify_type_war": "⚔️",
    "notify_type_cwl": "🏆",
    "notify_type_capital": "🏰",
    "notify_add": "➕",
    "notify_list": "📋",
    "notify_edit": "✏️",
    "notify_delete": "🗑",
    "notify_back": "⬅️",
    "notify_channel_dm": "✉️",
    "notify_channel_chat": "💬",
    "admin_notify_war": "⚔️",
    "admin_notify_cwl": "🏆",
    "admin_notify_capital": "🏰",
    "reminder_delay": "⏱️",
    "reminder_time": "🕒",
    "cancel": "❌",
    "ack": "✅",
    "token_help": "📖",
    "no_targets": "🚫",
    "admin_unclaim": "🛠",
}
