from __future__ import annotations

EMOJI: dict[str, str] = {
    "main_menu": "🏠",
    "register": "📝",
    "profile": "👤",
    "stats": "📊",
    "notifications": "🔔",
    "targets": "🎯",
    "rules": "📜",
    "complaint": "📣",
    "guide": "❓",
    "admin": "🛠",
    "show_profile": "👤",
    "refresh_stats": "🔄",
    "refresh": "🔄",
    "seasons": "🗓️",
    "back": "⬅️",
    "back_to_notifications": "⬅️",
    "notify_dm_menu": "🔔",
    "notify_dm_window": "🕒",
    "notify_channel_dm": "📩",
    "notify_channel_chat": "💬",
    "notify_rules_war": "⚔️",
    "notify_rules_cwl": "🏆",
    "notify_rules_capital": "🏰",
    "notify_rules_add": "➕",
    "notify_rules_active": "📋",
    "notify_rules_edit": "✏️",
    "notify_rules_delete": "🗑",
    "notify_rules_back": "⬅️",
    "nav_prev": "◀️",
    "nav_next": "▶️",
    "targets_select": "🎯",
    "targets_table": "📋",
    "assign_other": "🛠",
    "admin_clear": "🧹",
    "admin_diagnostics": "🩺",
    "admin_users": "👥",
    "admin_complaints": "📣",
    "admin_notify_chat": "🔔",
    "admin_notify": "🔔",
    "admin_notify_war": "⚔️",
    "admin_notify_cwl": "🏆",
    "admin_notify_capital": "🏰",
    "admin_reminder_delay": "⏳",
    "admin_reminder_time": "🕒",
    "ack": "✅",
    "cancel": "✖️",
    "delete": "🗑",
    "dm_enabled": "✅",
    "dm_disabled": "🔴",
    "toggle_on": "✅",
    "toggle_off": "🔴",
    "missed_attacks": "📋",
    "info": "ℹ️",
}
